### ISSUE TITLE
Some extra steps to get it working on M5Stack

### ISSUE THREAD

**Issue by GunterO** [tuupola/esp_effects#5]
Hi, thanks for your library, really nice work!
Anyway. I'm testing with a M5Stack Basic (black), on Windows 10 with IDF v4.1, and I had to take some extra steps to get it working. I'm quite a newbie here, so sorry if I made mistakes or are missing the obvious.

On compiling ($ idf.py build), I got these errors:
![image](https://user-images.githubusercontent.com/7931134/98555439-3b4ed300-22a2-11eb-91ad-5a7a4b913ea4.png)

To make them go away, I had to go into $ idf.py menuconfig and set this:
![image](https://user-images.githubusercontent.com/7931134/98555558-620d0980-22a2-11eb-9eaa-ec16c22df35b.png)
![image](https://user-images.githubusercontent.com/7931134/98555879-bca66580-22a2-11eb-8f60-def6101dbfb8.png)

And then the compiler gave no errors.

On uploading it to the device, all the colors were inverted. So I had to set:
![image](https://user-images.githubusercontent.com/7931134/98555679-849f2280-22a2-11eb-829d-45ba598de0ee.png)

Which made it run perfectly.

Is this as expected?

**Comment by tuupola** [comment]
There are ready made config files for different boards. I use [sdkconfig.m5stack](https://github.com/tuupola/esp_effects/blob/master/sdkconfig.m5stack) with M5Stacks. It should work with the black version too. Instructions how to use ready made config files are in the [README](https://github.com/tuupola/esp_effects/blob/master/README.md):

```
$ git clone git@github.com:tuupola/esp_effects.git --recursive
$ cd esp_effects
$ cp sdkconfig.m5stack sdkconfig
$ make -j8 flash
```

**Comment by GunterO** [comment]
Hi, thanks for your quick response.
Yes, this is the first step I did: $ cp sdkconfig.m5stack sdkconfig
But the e.g. CONFIG_AXP192_GPIO0_LDOIO0_VOLTAGE_BIT74 setting, where axp192_config.h is referring to isn't in there.

**Comment by tuupola** [comment]
Ah then it is a bug. I think I have updated the AXP192 library but not the default config files yet. Will check.

**Comment by tuupola** [comment]
I updated the AXP192 module to have default config values even when it is not used. Just tested and myself and both of the following now compile.

```
$ cp sdkconfig.m5stack sdkconfig
$ make -j8
```

```
$ cp sdkconfig.m5stack sdkconfig
$ idf.py build
```

**Comment by tuupola** [comment]
@GunterO Did this fix the problem for you too?

**Comment by GunterO** [comment]
Yes, it did, thanks! I'll close the issue.

**Comment by tuupola** [comment]
Thanks for the heads up! I had not compiled it for M5Stack for a while so missed the problem myself.
